### ISSUE TITLE
Support for interfaces/subclasses/parameterized enums?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/dataclass#10]
I want to implement a class structure for book content where the book chapters might be of different types. Something like the code example below. I can't find out a way to DataClass-ify this, though.

My first instinct is to implement the Chapter as an Haxe enum, but that would require parameterized enums wich DataClass currently doesn't support. I can't find a way to use interfaces or subclasses either - DataClass doesn't seem to like that.

So, iIs it possible to use DataClass in this situation? Would that maybe require writing a custom DC parser?

```
class Book  /*implements DataClass*/ {
    public function new() {}
    public var chapters:Array<IChapter>;
}

interface IChapter {}

class ChapterSimple /*implements DataClass*/ implements IChapter  {
    public function new() {}
    public var info:String = 'simple info';
}

class ChapterComplex /*implements DataClass*/ implements IChapter {
    public function new() {}
    public var markdown: String = '##markdown';
    public var subchapters: Array<IChapter> = [];
}
```

**Comment by ciscoheat** [comment]
Handling relations is where the border between Data management and ORM gets blurry. But there is a trick to use interfaces with DataClass, and that is to let the interface extend DataClass:

```haxe
interface IChapter extends DataClass
{
	public var info(default, set) : String;
}

// Is now a DataClass
class SimpleChapter implements IChapter
{
	public var info : String = 'simple info';
}

// Is now a DataClass
class ComplexChapter implements IChapter
{
	public var info : String = 'complex info';
	public var markdown : String;
}

class Book implements DataClass {
	public var chapters : Array<IChapter>;
	public var name : String;
}
```

And if you have some relation that cannot be a DataClass, you can exclude its field and add an argument to the constructor:

```haxe
class Book implements DataClass {
	public var chapters : Array<IChapter>;
	public var name : String;
	@exclude public var location : GpsPosition;

	public function new(data, ?location) {
		this.location = location;
	}
}
```

**Comment by cambiata** [comment]
Thank you!

Still have problem though - instantiating classes from code and export as json works fine, but importing the same json gives an exception.
Maybe the setter methods have to be elaborated..?

```
interface ITreeNode extends DataClass {
    public var id(default, set):String;
    public var children(default, set):Array<ITreeNode>;
}

class Book implements ITreeNode {
    public var id(default, set):String = 'Book id'; function set_id(v) return this.id = v;
    public var children(default, set):Array<ITreeNode> = []; function set_children(val) return this.children = val;

    public var bookSpecific: String = 'just for books';
}

class Chapter implements ITreeNode {
    public var id(default, set):String = 'Chapter id'; function set_id(v) return this.id = v;
    public var children(default, set):Array<ITreeNode> = []; function set_children(val) return this.children = val;
    
    public var chapterSpecific: Int = 1;
}

class Main {
    static public function main() {

        var book = new Book({id:'BookA', children:[new Chapter({id:'ChapterA'})]});

        // Exporting to json works fine:
        var json = book.toJson();
        // {bookSpecific: just for books,id: BookA,children: [{chapterSpecific: 1,id: ChapterA,children: []}]}

        // Importing the same json doesn't work:
        var book2 = Book.fromJson(json);
        // Uncaught exception Unexpected value VNull(null), expected array
    }
}

```

**Comment by ciscoheat** [comment]
There is no type information in the json, so DataClass cannot instantiate the data from an interface. This is a tricky breakpoint, since putting type information there would put it even closer to an ORM and all that entails.

A solution could be to create a custom json parser, inheriting from the current one.

**Comment by ciscoheat** [comment]
Added a `TypedJsonConverter`, update haxelib and check the docs!

**Comment by cambiata** [comment]
Thanx!

**Comment by ciscoheat** [comment]
I guess this can be closed as well?
