### ISSUE TITLE
TypedJsonConverter: Alternative name for $class field?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/dataclass#11]
It would be great to have the possibility to use an alternative field name for typed classes. In my case, "$class" can't be used - I am using Firebase document database, and "$" characters can't be used in field names.  Maybe an @classfieldname metafield or something?

**Comment by ciscoheat** [comment]
Fixed in https://github.com/ciscoheat/dataclass/commit/1f34086fe9e07ee3ad00ebf576f1f43092ac7eba
