### ISSUE TITLE
Compare for equality?

### ISSUE THREAD

**Issue by singpolyma** [ciscoheat/dataclass#13]
Do dataclasses get an `==` override or other method to compare for equality automatically generated?

**Comment by ciscoheat** [comment]
Hello, no there is no equality check involved at the moment. If you have an idea for it, I'm happy to take a look at it.

**Comment by ciscoheat** [comment]
The recommended way to do equality comparisons now is with the library [deep_equal](https://lib.haxe.org/p/deep_equal/).
