### ISSUE TITLE
Feature request : auto trim string fields

### ISSUE THREAD

**Issue by CedX** [ciscoheat/dataclass#15]
It's very common to trim string values before validating or assigning them to a data class, but it's also very annoying to do this yourself :

```haxe
new MyDataClass({
  field1: request.field1.trim(),
  field2: request.field2.trim(),
  field3: request.field3.trim()
});

MyDataClass.validate({
  field1: request.field1.trim(),
  field2: request.field2.trim(),
  field3: request.field3.trim()
});
```

It would be cool if it existed a `@:autoTrim` meta, or something like that, that handles the job for us:

```haxe
class MyDataClass implements DataClass {
  @:autoTrim
  final field1: String;

  @:autoTrim
  final field2: String;

  @:autoTrim
  final field3: String;
}
```

**Comment by ciscoheat** [comment]
Hi, that wasn't too much work to add, just needed to be careful with null values, so a new version has been released just now, using `@:trim` as metadata.

**Comment by CedX** [comment]
Wonderful! Thanks a lot 🥰
