### ISSUE TITLE
Feature: Map support?

### ISSUE THREAD

**Issue by modjke** [ciscoheat/dataclass#6]
It would be gread to support automatic conversion from json Dynamic to StringMap/IntMap with the proper key validaion, and nested DataClasses as values.
Example:

```
//json
{
    "stringMap": {
         "value_1" : 2.3,
         "value_2" : 0.3,
         "value_3" : 5.2,
    },
    "intMap": {
         "1": { "name" : "one" },
         "2": { "name" : "two" },
         "3": { "name" : "three" }
    }
}
```

```
//data classes
class Data implements dataclass.DataClass {
    public var stringMap:StringMap<Float>;
    public var intMap:IntMap<Item>
}
class Item implements dataclass.DataClass {
    public var name:String;
}

var data = Data.fromDynamic(haxe.Json.parse(json));
trace(data.stringMap.get("value_1")); //traces '2.3'
trace(data.intMap.get(1).name);  //traces 'one'
```

**Comment by ciscoheat** [comment]
Hi, interesting idea! Keeping this open so I can think about it. A problem is that it may easily expand into some kind of ORM, and I'd like to keep things simple first and foremost. :)

**Comment by ciscoheat** [comment]
Good news, now with version 1.1.0 of dataclass, StringMap and IntMap is supported. Enjoy!
