### ISSUE TITLE
Support for array of abstracts?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/dataclass#8]
Trying to use an array of abstracts in DataClass causes "Unsupported DataClass type" error.
See example code below.
Any way around this?

```
class Test implements DataClass {
    public var id:Int;
    public var aint:AInt; // Works fine!
    public var aints:Array<AInt>; // gives 'Unsupported DataClass type: AInt
}

abstract AInt(Int) to Int from Int {}
```

**Comment by ciscoheat** [comment]
That should work, I'll be back with a fix soon!

**Comment by ciscoheat** [comment]
New haxelib version released, also including some null safety features (check the documentation example).
